---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install some packages
      apt:
        name:
          - ntp
          - git
          - nano
          - curl
          - wget
          - vim
          - man
          - unzip
          - mysql-client
          - software-properties-common
        state: 'present'
      tags:
        - initial

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create docker code directory
      file: path=/docker state=directory owner=root group=root mode=0775

    - name: Install Docker Compose (if configured).
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755

    - name: Ensure /root/delectame/server directory exists.
      file:
        dest: /root/delectame/server
        mode: 0775
        owner: vagrant
        state: directory

    - name: copy commands
      copy:
        src: "{{ playbook_dir }}/commands"
        dest: /root/delectame/server

    - name: copy containers
      copy:
        src: "{{ playbook_dir }}/containers"
        dest: /root/delectame/server

    - name: generate commands
      command: sh /root/delectame/server/commands/generate-commands.sh