# Generated by Django 3.2.8 on 2021-10-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('uidentifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city_name', models.CharField(max_length=255)),
                ('popularity_rate', models.FloatField()),
                ('satisfaction_rate', models.FloatField(blank=True, null=True)),
                ('total_reviews', models.IntegerField()),
                ('average_price', models.FloatField()),
            ],
            options={
                'db_table': 'Restaurant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('uidentifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('average_popularity_rate', models.FloatField(blank=True, null=True)),
                ('average_satisfaction_rate', models.FloatField(blank=True, null=True)),
                ('average_price', models.FloatField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Segment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestaurantSegmentAssociation',
            fields=[
                ('segmentuid', models.OneToOneField(db_column='segmentUID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='crud.segment')),
                ('restaurantuid', models.ForeignKey(db_column='restaurantUID', on_delete=django.db.models.deletion.DO_NOTHING, to='crud.restaurant')),
            ],
            options={
                'db_table': 'Restaurant_Segment_Association',
                'managed': True,
                'unique_together': {('segmentuid', 'restaurantuid')},
            },
        ),
    ]
