version: '3'
services:

  sfexam:
    build:
      context: ./sfexam
      dockerfile: Dockerfile
    container_name: sfexam
    volumes:
      - /docker/sfexam:/var/www
    ports:
      - "9006:9006"
    environment:
      - VIRTUAL_HOST=sfexam.delectame.develop

  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mariadb:
    container_name: mariadb
    image: mariadb:10.4.12
    volumes:
      - /mariadb:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=delectaRoot1234!
    ports:
      - "3306:3306"
  
  mongodb:
    container_name: mongodb
    image: mongo:4.2.7
    volumes:
      - /mongodb:/data/db
    environment:
      - TERM=dumb
      - MONGO_INITDB_ROOT_USERNAME=delecta_root
      - MONGO_INITDB_ROOT_PASSWORD=delectaRoot1234!
    ports:
      - "27017:27017"
    command: mongod